### PR TITLE
Add spotless

### PR DESCRIPTION
**Pull request by Taz03**
- added spotless
- removed `.idea`

### CODE REVIEW

**Comment by wisskirchenj** [comment]
@Taz03 : Is it OK, if we close this now? We are using SonarLint and -Qube now for SCA and other suggestions are way in merge conflicts...

**Comment by Taz03** [comment]
Yea sure

**Comment by wisskirchenj** [comment]
We are using SonarLint and -Qube now for SCA and other suggestions are way in merge conflicts...

**Comment by wisskirchenj** [comment]
We are using SonarLint and -Qube now for SCA and other suggestions are way in merge conflicts...

**Pull request closed without merging**
